import type { Metadata } from "next";
import PracticePage, { type PracticeSolution } from "../practice-page";

export const metadata: Metadata = {
  title: "Automation in Practice — Zetbros",
  description: "Detailed automation problems and the workflow, integration and AI-agent systems Zetbros can build.",
};

const solutions: PracticeSolution[] = [
  {
    id: "workflow-automation",
    icon: "⚙️",
    title: "Workflow Automation",
    summary: "Automate repeatable multi-step office work while keeping people involved where judgement, approval or exception handling is required.",
    problem: "Employees often spend time on work that is not difficult but is repeated constantly: read an email, download an attachment, rename a file, copy values into a spreadsheet, update another system and notify someone. The employee becomes the workflow engine between tools.",
    solution: "Zetbros can map the current process, identify the deterministic and repetitive steps, connect the systems involved, automate the repeatable path and leave clear exception or approval points for the steps that still need a person.",
    detail: "We begin by observing the real workflow rather than designing from assumptions. Each step is classified as deterministic, data-dependent, judgement-based or policy-sensitive. APIs and webhooks are preferred where available; scripts, scheduled jobs, browser automation or AI-assisted extraction can be used where appropriate.",
    flow: ["Observe current process", "Map decisions + exceptions", "Connect systems", "Automate repeatable steps", "Human approval / exception", "Monitor + improve"],
    build: ["Workflow mapping", "Triggers and schedules", "API / webhook integrations", "File handling", "Validation rules", "Browser automation where needed", "Human approval steps", "Exception queue", "Retries and alerts", "Operational logs"],
    deliverables: ["Current-state workflow map", "Automation design", "Implemented workflow", "Exception / approval path", "Run history and logging", "Monitoring / alerts", "Test cases", "Operations runbook"],
    control: "Not every repeated task should be fully automated. Steps with financial, security, customer or compliance impact may need explicit human approval, and UI-based automation should be monitored because it is more fragile than a supported API.",
    outcome: "Routine movement of information can happen consistently in the background while employees spend more time on exceptions, decisions and work that actually requires a person.",
  },
  {
    id: "document-automation",
    icon: "📄",
    title: "Intelligent Document Processing",
    summary: "Turn invoices, orders, quotations, forms and reports into validated structured data without assuming every document uses the same template.",
    problem: "Companies receive semi-structured documents from many suppliers, customers or internal teams. The same business fields may appear in different layouts, so fixed templates break and employees end up reading every document manually before entering the data somewhere else.",
    solution: "Zetbros can combine document ingestion, OCR or parsing, AI-assisted extraction, deterministic validation, duplicate checks and a human-review screen for uncertain or policy-sensitive cases.",
    detail: "The design starts from the target fields and the downstream system. We collect representative documents, measure extraction quality, define validation rules and confidence thresholds, then route uncertain cases to a reviewer rather than silently accepting low-confidence output.",
    flow: ["Email / file arrives", "OCR / parse", "Classify document", "Extract structured fields", "Validate + confidence check", "Human review if needed", "ERP / CRM / database"],
    build: ["Email / file ingestion", "OCR or native PDF parsing", "Document classification", "LLM-assisted extraction", "Schema validation", "Duplicate detection", "Confidence scoring", "Human-review UI", "Database / API integration", "Audit trail"],
    deliverables: ["Document sample assessment", "Extraction schema", "Processing pipeline", "Validation rules", "Review workflow", "Downstream integration", "Accuracy / exception test set", "Operations documentation"],
    control: "AI extraction should not be treated as infallible. Important financial or contractual fields can require deterministic validation or human review, and the acceptable confidence threshold should be based on the business risk of an incorrect value.",
    outcome: "Document-heavy workflows become easier to process at scale while uncertain cases remain visible instead of being hidden inside an automated pipeline.",
  },
  {
    id: "system-integration",
    icon: "🔗",
    title: "System Integration Automation",
    summary: "Connect the tools the company already uses so employees no longer have to copy information from one system into another manually.",
    problem: "A company may already have a CRM, ERP, email platform, ticketing system, spreadsheets, databases and internal applications that work individually but do not exchange the information the business process needs.",
    solution: "Zetbros can build an integration layer using the interfaces each system actually exposes: REST APIs, webhooks, databases, file exchange, SFTP, queues, identity APIs or custom connectors.",
    detail: "We define the source of truth for each field, the event that should trigger synchronization, the expected data model and what should happen when one system is unavailable. The integration includes retries, idempotency or reconciliation where needed rather than assuming every request succeeds once.",
    flow: ["Source event", "Integration layer", "Transform / validate", "Target systems", "Retry / reconcile failures", "Operational visibility"],
    build: ["REST API integrations", "Webhooks", "Database synchronization", "File / SFTP workflows", "Queues", "Identity integrations", "Data transformation", "Custom adapters", "Retry logic", "Reconciliation jobs", "Operational logging"],
    deliverables: ["System / field mapping", "Integration architecture", "Connector implementation", "Data transformation rules", "Failure handling", "Monitoring and alerts", "Runbook", "Handover documentation"],
    control: "Where a supported API exists, it is generally safer and more maintainable than automating a user interface. Access credentials should be scoped to the minimum permissions required, and cross-system data ownership must be defined before synchronization begins.",
    outcome: "Information can move between business systems through a controlled integration layer with fewer manual handoffs and clearer ownership of failures.",
  },
  {
    id: "legacy-automation",
    icon: "🖥️",
    title: "Legacy Software Automation",
    summary: "Modernize a workflow around an older application without requiring the company to replace that application immediately.",
    problem: "A critical legacy application may have no modern API or webhook but still run an important business process. Replacing it may be expensive, risky or simply not a priority, so employees continue operating it manually as the bridge to newer systems.",
    solution: "Zetbros can evaluate safer ways to automate around the existing application: browser or desktop automation, customer-approved database integration, scheduled imports and exports, file exchange or email-triggered workflows.",
    detail: "We first determine what interfaces the system genuinely supports and what the vendor or customer permits. UI automation is treated as a last-mile adapter with explicit failure detection because changes to screens, timing or session behavior can break an unattended robot.",
    flow: ["Modern trigger", "Automation layer", "Legacy interface", "Perform bounded task", "Read result", "Return to modern system"],
    build: ["Browser automation", "Desktop automation", "Approved database access", "CSV / Excel / XML flows", "SFTP exchange", "Email triggers", "Scheduled imports / exports", "Failure screenshots / alerts", "Run history", "Recovery procedure"],
    deliverables: ["Legacy-interface assessment", "Automation method recommendation", "Implemented adapter", "Failure detection", "Test cases", "Recovery / restart procedure", "Monitoring", "Maintenance notes"],
    control: "Legacy automation can be more fragile than API integration. We avoid unsupported database writes or hidden interfaces unless the customer explicitly approves the method and the technical risk has been understood.",
    outcome: "The company can improve a repetitive process now while preserving the option to replace or modernize the legacy system later on its own schedule.",
  },
  {
    id: "reporting-automation",
    icon: "📊",
    title: "Reporting Automation",
    summary: "Turn recurring data collection, calculation, visualization and distribution into a reproducible pipeline.",
    problem: "Weekly or monthly reports are often rebuilt manually from spreadsheets, databases, CRM data, ticket systems and other sources. The calculations may be identical every cycle, yet someone still spends time gathering and formatting them before the report can be reviewed.",
    solution: "Zetbros can connect the approved data sources, standardize the transformations and business calculations, generate the required report or dashboard and distribute it on a schedule. AI can optionally draft commentary on notable changes for human review.",
    detail: "We separate deterministic reporting logic from AI-generated interpretation. Numbers, filters and calculations are defined in code or queries; AI is used only where natural-language explanation adds value, and generated commentary can be reviewed before distribution when the report is business-sensitive.",
    flow: ["Source systems", "Collect + clean data", "Business calculations", "Report / dashboard", "Optional AI commentary", "Review / distribute"],
    build: ["Source connectors", "Data-cleaning pipeline", "Business calculations", "Scheduled jobs", "Charts / dashboards", "PDF / spreadsheet report generation", "Optional AI summary", "Email / chat distribution", "Run monitoring"],
    deliverables: ["Source and metric definition", "Data pipeline", "Report template or dashboard", "Schedule", "Distribution workflow", "Optional review step", "Monitoring", "Calculation documentation"],
    control: "AI commentary should not redefine the underlying metrics. Important figures come from deterministic calculations and traceable data sources; generated explanations are an optional layer on top of those results.",
    outcome: "Recurring reporting becomes consistent and repeatable, with people spending less time reconstructing the same report and more time reviewing what the data means.",
  },
  {
    id: "controlled-ai-agents",
    icon: "🤖",
    title: "Controlled AI Agents",
    summary: "Use AI for operational work that requires reading context and choosing among approved tools, without giving the model unrestricted company access.",
    problem: "Some business processes are too contextual for simple rules. An employee may need to read a ticket, understand the issue, search another system, compare earlier communications and decide which approved next step should be proposed.",
    solution: "Zetbros can build a bounded agent workflow with narrowly scoped tools, explicit permissions, deterministic checks, human approval points and an audit trail of every attempted action.",
    detail: "We define what the agent is allowed to read and do before connecting tools. Read-only research and preparation can often be automated first. High-impact writes can require approval, and unexpected tool responses cause the workflow to stop or escalate rather than improvise silently.",
    flow: ["Trigger", "Read approved context", "Choose approved tool", "Collect / reason", "Propose action", "Human approval if required", "Execute + log"],
    build: ["Agent orchestration", "Tool connectors", "Scoped credentials", "Context retrieval", "Deterministic guardrails", "Approval UI", "Audit logs", "Error handling", "Retry / escalation logic", "Operational monitoring"],
    deliverables: ["Agent scope definition", "Permission map", "Workflow implementation", "Tool integrations", "Approval model", "Audit trail", "Adversarial / failure test cases", "Operations runbook"],
    control: "The goal is controlled execution, not maximum autonomy. An agent should not receive broad credentials simply because it can reason about a task, and sensitive actions should retain an appropriate human or deterministic control point.",
    outcome: "AI can assist with multi-step operational work while the company retains visibility and control over the actions that affect real systems.",
  },
  {
    id: "intelligent-mailbox",
    icon: "📧",
    title: "Intelligent Mailbox",
    summary: "Turn a shared mailbox from a human routing queue into a structured intake process with classification, extraction and controlled actions.",
    problem: "Shared mailboxes such as support, orders, procurement or operations often require someone to read each message, identify the request type, download attachments, find the customer or account, create a ticket and route the work to the right team.",
    solution: "Zetbros can build an intake workflow that classifies incoming messages, extracts relevant fields and attachments, matches internal context, creates or updates records and drafts the next action for a person to approve where appropriate.",
    detail: "We start with the mailbox categories and the actions that are safe to automate. Classification and extraction are measured on representative messages. High-confidence low-risk routing may be automatic, while customer-facing responses or unusual cases can remain in a review queue.",
    flow: ["Incoming email", "Classify", "Extract fields / attachments", "Match account / process", "Create task / draft response", "Human review where needed"],
    build: ["Mailbox ingestion", "Classification", "Urgency detection", "Attachment handling", "Structured extraction", "Account lookup", "Ticket / ERP / CRM integration", "Draft replies", "Routing rules", "Exception queue"],
    deliverables: ["Mailbox category model", "Processing workflow", "System integrations", "Review queue", "Routing / escalation rules", "Audit trail", "Monitoring dashboard", "Operations guide"],
    control: "We do not recommend an initial design where AI automatically replies to every message. Customer-facing or high-impact actions can start as drafts or recommendations and become more automated only after the workflow has been measured and trusted.",
    outcome: "The mailbox becomes a structured operational intake channel rather than relying on an employee to manually route every message from scratch.",
  },
  {
    id: "approval-workflows",
    icon: "✅",
    title: "Approval Workflow Automation",
    summary: "Replace email chains and status chasing with structured requests, permissions, approval history and visible state.",
    problem: "Many internal approvals happen through email or chat: someone requests something, a manager replies, finance asks for more data, the requester loses track of status and nobody has one complete audit trail of who approved what and when.",
    solution: "Zetbros can build a digital approval workflow that captures the request, validates required fields, sends it to the right approver, records decisions, reminds overdue participants and triggers the downstream action only after the required approval state is reached.",
    detail: "We map the approval matrix, thresholds and exception rules first. The workflow can integrate with existing identity, finance, ticketing or procurement systems where suitable interfaces exist, while keeping the request history and decision chain visible.",
    flow: ["Employee request", "Validate", "Route to approver", "Decision + history", "Additional approval if required", "Execute / notify"],
    build: ["Request forms", "Approval routing", "Threshold rules", "Reminders", "Role permissions", "Status dashboard", "Audit history", "Downstream API integration", "Notifications", "Exception handling"],
    deliverables: ["Approval matrix", "Workflow implementation", "Request / review UI", "Audit history", "Notifications", "Integration logic", "Test scenarios", "Admin documentation"],
    control: "Automation can route and enforce the process, but the business remains responsible for defining who has authority to approve each class of request. AI may flag anomalies or summarize requests without replacing the authorized decision-maker.",
    outcome: "Requesters and approvers can see the state of a process clearly, while the organization keeps a structured record of decisions instead of reconstructing them from email threads.",
  },
  {
    id: "employee-lifecycle",
    icon: "👤",
    title: "Employee Onboarding & Offboarding Automation",
    summary: "Coordinate identity, application, ticket and asset steps from an approved HR event so access changes are less dependent on manual handoffs.",
    problem: "When an employee joins or leaves, HR, IT, managers and application owners may each have separate manual steps. Missing one onboarding step creates delays; missing an offboarding step can leave access or sessions active longer than intended.",
    solution: "Zetbros can orchestrate an approved lifecycle workflow from the HR or identity event through tickets, groups, applications, equipment requests, notifications and verification steps supported by the customer’s systems.",
    detail: "We build around the company’s identity and HR authority model. The automation only changes systems that expose suitable supported interfaces and only with permissions approved by the customer. Offboarding receives particular attention to sequencing, session revocation and verification.",
    flow: ["Approved HR event", "Identity workflow", "Groups / applications", "IT tasks / assets", "Manager notifications", "Verification + audit"],
    build: ["HR event integration", "Identity provisioning", "Group membership", "Application provisioning where supported", "IT ticket creation", "Asset request / return workflow", "Session-revocation steps", "Manager notifications", "Completion verification"],
    deliverables: ["Lifecycle system map", "Provisioning / deprovisioning workflow", "Permission scopes", "Ticket / identity integrations", "Verification checklist", "Audit trail", "Failure escalation", "Operations runbook"],
    control: "Identity changes are security-sensitive. The source of truth, approval authority and sequencing must be explicit, and unsupported direct manipulation of applications should not be introduced merely to maximize automation coverage.",
    outcome: "Joiner and leaver processes become more consistent and auditable, with fewer critical steps depending on someone remembering to send the next email manually.",
  },
  {
    id: "automation-assessment",
    icon: "🔍",
    title: "Automation Opportunity Assessment",
    summary: "A low-risk entry project for companies that know work is repetitive but do not yet know which process is worth automating first.",
    problem: "Teams often feel overloaded by repetitive work but have no measured view of which workflows consume the most time, which ones are stable enough to automate and which automation would deliver useful value relative to implementation effort and operational risk.",
    solution: "Zetbros can observe selected workflows, measure their current manual effort, map the systems and decision points, identify automation candidates and rank them by potential business value, implementation complexity and risk.",
    detail: "Rather than inventing savings in advance, we collect the customer’s real frequency and handling-time data where available. Each candidate is assessed for API availability, process stability, exception rate, permissions, data sensitivity and how much human judgement is actually required.",
    flow: ["Select team / process", "Observe + measure", "Map workflow", "Identify candidates", "Estimate effort / value / risk", "Prioritized roadmap"],
    build: ["Workflow interviews", "Process observation", "Manual-effort measurement", "System / integration inventory", "Automation feasibility review", "Risk assessment", "Candidate scoring", "Pilot recommendation", "Roadmap"],
    deliverables: ["Workflow inventory", "Current-state maps", "Measured baseline where available", "Automation candidate list", "Effort / value / risk ranking", "Recommended pilot", "Implementation roadmap", "Assumptions and data gaps"],
    control: "Potential savings are estimates until an automation is implemented and measured in production. We keep assumptions visible and distinguish observed data from inferred opportunity so the customer can make an informed investment decision.",
    outcome: "The company gets a prioritized, evidence-based automation roadmap instead of starting with a vague request to 'add AI' to every process.",
  },
];

export default function AutomationInPracticePage() {
  return (
    <PracticePage
      category="Automation"
      title="Stop using people as the connection between software."
      lead="If a team repeatedly moves information from one place to another, there is usually a workflow worth examining. Zetbros connects existing tools, data and processes so repetitive work can run reliably without forcing the company to rebuild every business system first."
      solutions={solutions}
      related={[
        { href: "/ai-in-practice", title: "AI in practice", text: "Add governed AI understanding where rules are not enough" },
        { href: "/infrastructure-in-practice", title: "Infrastructure in practice", text: "Connect automation to the physical environment" },
      ]}
    />
  );
}
